apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
- ../../base
images:
- name: rahulnayak11631/bluegreen-demo
  newName: rahulnayak11631/bluegreen-demo
  newTag: 28ea61b
patches:
- path: patch-ingress.yaml
  target:
    kind: Ingress
    name: bluegreen-demo
- path: patch-rollout.yaml
  target:
    kind: Rollout
    name: bluegreen-demo
